language: ruby
rvm:
- 1.9.3
gemfile:
- Gemfile
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-zookeeper-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: gDJaqOAe2pqkKGPAh3DjeBanwYNibpSJDRbFFL2D2PQVbGTKMxpmvKlItfhAqf9UFs6x0PJtou87DVgVgIqoCAD9jLky8OT8TkSBtwHuJXlYZxD4DWFwbDMK9oXBBvUvjjidhq3UO0yfdSUZ3Wn0nRQlM4e4YggTtiZhNl/PyU0=
  - secure: Li6ZSGqGpr1r2xvLYlNNlcZF4xU96JLRtZQvapfChYQT8Ej4FpQd2utN8zB+6qm2pYnCa0ERtrfyw64prXXda1ltupa15phX81JkK2LX2dG3vwQhtqbf9bU3BZ/0QZYwFABflZdHUzItFx6r6f836UNXvhlToO/h2/TJSTpDZzI=
  - secure: qgAJyKy/+UcEDFCepFghfKuBNE56Sav8qGqk4ryFG3F6xeb0x2s/nkVc6uwCo94/29U2u9FceRmGQbb6BzXGhqLscgBmHhxX7g0q1pc5IGTAD83hMcMIL38ef21g/2N58Bvapm/pBRBUjkA0UVvO58Rm2AoqpJdmryvjyPrLDlU=
  - secure: P2Qh7EERrgCc+urinDWVtuyH1y5zRon4hBFb44rlJ+NqHU6cZg6xWWKV+VpXU+XdZkRCcK3DsQOCpTKBqKPbUnL2nzt2UZev0XK4cRAvR3j7DW2Ap6PrMrRbImKVAi4Z61y7ofGpZJgcwlMJbhkCXi73QBUWXXAu+aJj4qxuzVg=
  - secure: QcVL3ysWCZYL6ESpZR1c4naJFk1+18LSZI3dp3v63xJxeHoYbvzsjw1kmanzjfuTwWlCTAeSdn27N2FbxeKha5qINCJyJSkFHEXcj8sNHqr//GaiNmREs/ySI6xU7WOMCiZtqMjfiyybkaM37PlDTuRJleWUgWyYxiJ58g2s2Bk=
  - secure: Mpx99y/5sWqV85HAmY4PZMi42iRbuWvb2YlWou1TL9geLMaE0DFDUVLx/33vBZFBbaqNxMxCko8mbNNWSMpUt+2qtbGwCXv7HL5bqWY6ezXlWFPL/4RjT9wrjwa2zxoDQwYETPwbzW6Y824Ix6KjshuUqK+zKKZMI2VrB+SywQM=
  - secure: EECWv3Ha9gSpeFJCs6it7I9BT7cPmUBjK3BOKEOWmKKECW+PfBjuZjfEZo7MRLj4OlRLhaloU13mflU/mKBr/n83+XnDI6c/QRXH7PE26r8Ukcz2UtQ1iPPo6pFv7umt14ggG5BFdCesiBZUtG6jnBDnpCbl/7RKwC3IXwm7aro=
  - secure: aBjYB8ycr6kE3fwv6oGMtyoY6EW6v7jfpWv8IADexwqAxQu74wQY4sg3DN+1O3641DHJSey6/aYC54AYF/v77jLy6awLq3leJJzAeWUV73CMcUYXfwDuJaLvp6nwXXkqynI7dL/HL/C9JawQ6oJYjs0GQnLO2MAe0bgwbjkrk0M=
install:
- sudo apt-get -y -q install python-pip
- sudo pip install -r test/requirements.txt
before_script:
- gem install --version 2.0.15 berkshelf --no-ri --no-rdoc
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
