language: ruby
rvm:
- 1.9.3
gemfile:
- Gemfile
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-broadleaf-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: IyU/9QFIQQlWWGcd+Bhy648UBWtS/6uP/qMRGTRIX6kH6B7GJrLCiZFeg9si+ScvFcUJ46wWThzJ63jODeHBG77T64knfkqsxGpYKKMQhFRXcxrLbuOFG2ouife00w6j2zd0F2A9+u+AjxVfKOgToXfcncAMT3y6u0fbEkCNhQ0=
  - secure: U4R6b1p3gRs50b0/rCnr6qauNasoiT2/SsqNLl6LNTWKs6x08oAs39gkQ4sM+eNk1UHwGlscC/JPCLgNvdIfsdf18ezP3b57wO6JLFVZiamNwoq/0jnxuo0AtK97aRxeNLlzTGQAGNmgnH/QPSCEjOCAgM2XiLAKguNxPZ7Lrrc=
  - secure: Zgr59Qd/N0wlI5xAxNdl+LPlh3D9/UC4/izcGj0N+rG/QNwreZDrIRvrkupTAHH27eqBdZmIjqDkKGaktuVgzUyrWaTMrSIB//q+u+Sef2YduXb+otneZIGAwb3KaClmliM2I8cSNznqZKfd7L1M7Dpyyq5l9ct+H/RiUpjjjLQ=
  - secure: W6Z9QBPhDTkONZULSmQDc+zRii7+8qVUwjBNIy4Xgdsgb/7tq+1iowUiJ2J922G31xY/orRqBLTFVjnt+HqeGhpO1p9IWpzUc2P9rcWDi0354/WgxzHNlTTJscYKa5QPk/w2Tq2NKoZ2nivsVlvxgZDF99sdTy/KyX3VQy6f8GQ=
  - secure: Pvkn6MJdaG8+FsCFiY8aQe3rbu3/bW4XmnANxQD+aHi9e/PfFXZ28oEVzv1fqOLVDXudFie93HSe9ihBmMlCmzx4vFxgka8UhWXMcxHzn4V4214b2Lu1voeAGbOIw2MlDztanmu49b6CnJe5+Cc1jAmsOpV4y0eg7B+xv9cg78c=
  - secure: e7aItktbVvM8qqm3OBz1YFB8VMYHQ7YtYKvbdOl7z4/S/diw/3qNXfEl1uwDCy3H68ojnRbMvDIp184Yw4Cm04ElVrGYLK2Iwo71JPR01InTugSeY+KIEPfEZeY7FqQamAES4YBFzPepi4HgwYBwsouPthu3X7oCc9hgyEwH6GY=
  - secure: ekMiUhi4t54d7hViT+HgA6pAfXGWTnpvTYwyR2j920PGHnywzxiF8DIW6XaV8OTKKrlFtobBdI58y9LU5d9/3x0bb5G1ZdGqparmDZPMv0gJHPEJJnKNFxc6DR4y8cyMsfcOZ3Kwcq990PjzkbXK1bxyoMnCe5+puKKS6ssUL7k=
  - secure: ItgV5TWHMcTKU3zYIH61sPSXWbSN4+yP/TJlDn0MhZMUs6H8rzoqxBCXXQQyrHxyx9BYPCJoMntjOPxQTarW6HJrA/RSRwzaOGURBUWDDFDsBXTFqdGTzcl995cKQC/Hz7QocpeUF3ihaVO5fhqn6Nq8Zvg/H3L7+DX+0o04D+8=
  - secure: YYLFOwFv56eyfxlO3fPRLbgjR13QqNZdffMbu+6viudFR3/yuuzgIdz5WoJMFXWrT5NAdgmrKhKcmDSGTkqpQeEYy9QKN1gLjNXSUGX/q/Yenpbt/oFfzvM7PcO9P4vkQpRXwwq+9tOVSbKbVaIIKpqo9NnEVQckL16Usbd4M8Q=
install:
- sudo apt-get -y -q install python-pip
- sudo pip install -r test/requirements.txt
before_script:
- gem install --version 2.0.15 berkshelf --no-ri --no-rdoc
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
