kit:
  name: "Zookeeper"
  link: https://github.com/qubell-bazaar/component-zookeeper-dev 
  applications:
    - name: "Zookeeper"
      manifest: https://raw.github.com/qubell-bazaar/component-zookeeper-dev/2.0.37p/component-zookeeper-dev.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
        * Ports 2181, 3888 and 8090 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
